{"name": "Ошибка при попытке принять заказ без или с неверным id курьера", "status": "passed", "description": "Ошибка при попытке принять заказ без или с неверным id курьера.", "steps": [{"name": "Получение заказа по трек-номеру.", "status": "passed", "parameters": [{"name": "track", "value": "181068"}], "start": 1733420325067, "stop": 1733420325153}, {"name": "Принятие заказа курьером.", "status": "passed", "parameters": [{"name": "order_id", "value": "386381"}, {"name": "courier_id", "value": "None"}], "start": 1733420325153, "stop": 1733420325207}], "parameters": [{"name": "courier_id", "value": "None"}, {"name": "expected", "value": "(400, 'Недостаточно данных для поиска')"}], "start": 1733420325066, "stop": 1733420325207, "uuid": "c099275c-d837-45c0-a668-8c8b16093aa9", "historyId": "ce09601f2caa154dc4f3db47f5113bee", "testCaseId": "abe11c86ff0e6a83e2122a43b64dc9d7", "fullName": "tests.orders.test_orders_accept.TestOrdersAccept#test_accept_order_no_or_wrong_courier_id_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "14132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_accept"}]}