{"name": "Ошибка при попытке принять заказ без или с неверным id курьера", "status": "passed", "description": "Ошибка при попытке принять заказ без или с неверным id курьера.", "steps": [{"name": "Получение заказа по трек-номеру.", "status": "passed", "parameters": [{"name": "track", "value": "890063"}], "start": 1733420192264, "stop": 1733420192362}, {"name": "Принятие заказа курьером.", "status": "passed", "parameters": [{"name": "order_id", "value": "39109"}, {"name": "courier_id", "value": "None"}], "start": 1733420192362, "stop": 1733420192419}], "parameters": [{"name": "courier_id", "value": "None"}, {"name": "expected", "value": "(400, 'Недостаточно данных для поиска')"}], "start": 1733420192263, "stop": 1733420192420, "uuid": "cfe07066-73f4-4eeb-85e3-710bded4edcb", "historyId": "ce09601f2caa154dc4f3db47f5113bee", "testCaseId": "abe11c86ff0e6a83e2122a43b64dc9d7", "fullName": "tests.orders.test_orders_accept.TestOrdersAccept#test_accept_order_no_or_wrong_courier_id_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_accept"}]}