{"name": "Успешное получение заказов в виде списка", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = code_expected_and_data_in_body(<Response [504]>, *(200, 'orders', <class 'list'>))\n +    where (200, 'orders', <class 'list'>) = Orders.ORDERS_LIST", "trace": "self = <orders.test_orders_get.TestOrdersGet object at 0x000001C4BD518FD0>, orders_methods = <endp_methods.orders_methods.OrdersMethods object at 0x000001C4BD544580>\n\n    @allure.title('Успешное получение заказов в виде списка')\n    def test_get_orders_as_list_success(self, orders_methods):\n        '''Успешное получение заказов в виде списка.'''\n        response = orders_methods.get_all_orders()\n>       assert code_expected_and_data_in_body(response, *Orders.ORDERS_LIST)\nE       AssertionError: assert False\nE        +  where False = code_expected_and_data_in_body(<Response [504]>, *(200, 'orders', <class 'list'>))\nE        +    where (200, 'orders', <class 'list'>) = Orders.ORDERS_LIST\n\ntests\\orders\\test_orders_get.py:14: AssertionError"}, "description": "Успешное получение заказов в виде списка.", "steps": [{"name": "Получение всех заказов.", "status": "passed", "start": 1733420194081, "stop": 1733420254143}], "start": 1733420194081, "stop": 1733420254143, "uuid": "57359bcb-536c-4aad-bf95-6fc202596bb4", "historyId": "ccaf40f2a04d846ab3d6b87f5f4ba171", "testCaseId": "ccaf40f2a04d846ab3d6b87f5f4ba171", "fullName": "tests.orders.test_orders_get.TestOrdersGet#test_get_orders_as_list_success", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_get"}, {"name": "subSuite", "value": "TestOrdersGet"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "12392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_get"}]}