{"name": "Ошибка при попытке принять заказ без или с неверным id заказа", "status": "passed", "description": "Ошибка при попытке принять заказ без или с неверным id заказа.", "steps": [{"name": "Авторизация курьера.", "status": "passed", "parameters": [{"name": "account_data", "value": "{'firstName': 'cXXOdTZAiD', 'login': 'NRtcXdUEvu', 'password': 'ddTTLjigGY'}"}], "start": 1733420325631, "stop": 1733420325697}, {"name": "Принятие заказа курьером.", "status": "passed", "parameters": [{"name": "order_id", "value": "0"}, {"name": "courier_id", "value": "429200"}], "start": 1733420325697, "stop": 1733420325775}], "parameters": [{"name": "order_id", "value": "0"}, {"name": "expected", "value": "(404, 'Заказа с таким id не существует')"}], "start": 1733420325631, "stop": 1733420325775, "uuid": "5dc939f4-5c65-4815-8096-60416dd7c408", "historyId": "417b180a8c11ac03cd923507d1810202", "testCaseId": "bfea77d0d0d5feb53437bd736cae6341", "fullName": "tests.orders.test_orders_accept.TestOrdersAccept#test_accept_order_no_or_wrong_order_id_error", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "ZenBook"}, {"name": "thread", "value": "14132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_orders_accept"}]}